### ISSUE TITLE
Package names are a bit ugly

### ISSUE THREAD

**Issue by voghDev** [Vampiire123/Android-Design-Patterns#1]
I've noticed these package names:

`builder_example`
`decorator_example`
`singleton_example`
`strategy_example`

maybe they don't follow usual Java/Kotlin naming conventions. I would name them just `builder`, `decorator`, `singleton`, etc. So the reader of the code immediately guesses what can be found inside the package :)

What do you think?

**Comment by Vampiire123** [comment]
Yeah, you are right, I will change it!
